name: BlueGens
version: ${project.version}
main: me.blueslime.bluegens.BlueGens
api-version: 1.13
authors: [ JustJustin ]
softdepend:
  - PlaceholderAPI
  - Vault
author: JustJustin
description: ${project.description}
commands:
  bluegens:
    description: Main Command of the plugin